config/routes.rb
Rails.application.routes.draw do
  resources :jobs

  root to: "jobs#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, :location, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
    @stripe_data = OpenStruct.new(amount: 5000, email: 'test90@email.com')
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @stripe_data = OpenStruct.new(amount: 5000, email: 'test90@email.com')
    @job = Job.new(job_params.merge(amount: @stripe_data.amount))

    payment = ProcessPayment.new(
      params[:job][:stripe_token],
      @stripe_data.amount,
      @stripe_data.email
    )

    payment.run if @job.valid?

    respond_to do |format|
      if payment.error.blank? && @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        @job.errors.add(:base, :payment, message: payment.error)

        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :location, :description, :remote, :job_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true, html: {class: 'job-form'}) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :job_title, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :job_location, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :job_description, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :job_type %>
    <%= form.select :job_type, ['Permanent', 'Contract'], {prompt: 'Select job type'}, id: :job_type, class: 'input' %>
  </div>

  <div class="field">
    <%= form.check_box :remote, id: :job_remote, class: 'input' %>
    <%= form.label :remote, style: "float:left;" %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: 'job-submit-btn'%>
  </div>
<% end %>

<% if job.new_record? %>
  <script type="text/javascript">
    $(function() {
      var email, amount;

      email = '<%= @stripe_data.email %>';
      amount = <%= @stripe_data.amount %>;

      StripeButton('<%= Rails.configuration.stripe[:publishable_key]  %>', {email: email, amount: amount});
    });
  </script>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Description</th>
      <th>Job Type</th>
      <th>Remote?</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.location %></td>
        <td><%= job.description %></td>
        <td><%= job.job_type %></td>
        <td><%= job.remote? %></td>
        <td><%= job.amount %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @job.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <script src="https://checkout.stripe.com/checkout.js"></script>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>